version: '3.8'

services:
  db:
    image: postgres
    container_name: crud_dock
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: crudo
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: nest_app
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run start:dev
